<template>
  <div>
             <TOP v-show="show"></TOP>
    <h1 class="container is-fluid is-size-3">MYSELF</h1>
    <div class="columns">
      <div class="column is-two-five">
              <br>
              <img class="gif" src=".././assets/MYSELF.jpg"  alt="画像を表示出来ません">      
      </div>
      <div class="column is-thirds-five write">
        <br>
        名前：伊藤匡哉（いとうまさや）
        <br>
        <br>
        年齢：29歳（1990/12/22生まれ）
        <br>
        <br>
        学歴：岡崎西高校普通科 >> 名城大学理工学部建設システム工学科 
        <br>
        <br>
        職歴：自動車部品メーカー（６年） >> SES（４か月）
        <br>
        <transition>
        <p class="text-focus-in">詳しくはスキルページへ</p>
        </transition>
        <br>
        <!-- <br> -->
        性格：話しやすいとよく言われます
        <br>
        <br>               
        趣味：音楽、ゲーム、ドライブ
      </div>
    </div>
  </div>
</template>

<style>
  /* @import "C:/Users/Masaya/Desktop/my-project/node_modules/bulma/bulma.sass"; */
p {
  /* font-family: YuGothic, 游ゴシック,"Yu Gothic", "Noto Sans Japanese", sans-serif; */
  text-align:center;
    /* font-size:30px; */
  font-weight: bold;
  /* margin-top: 50px; */
}
.text-focus-in {
    -webkit-animation: text-focus-in 1.5s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
            animation: text-focus-in 1.5s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2018-11-27 15:52:19
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation text-focus-in
 * ----------------------------------------
 */
@-webkit-keyframes text-focus-in {
  0% {
    -webkit-filter: blur(12px);
            filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
            filter: blur(0px);
    opacity: 1;
  }
}
@keyframes text-focus-in {
  0% {
    -webkit-filter: blur(12px);
            filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
            filter: blur(0px);
    opacity: 1;
  }
}
</style>